DROP DATABASE IF EXISTS UStorage;
CREATE DATABASE UStorage;
USE UStorage;

CREATE TABLE User(
  userID INT NOT NULL AUTO_INCREMENT,
  nickname VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  photo VARCHAR(255) NOT NULL,
  PRIMARY KEY (userID)
);

CREATE TABLE File(
  fileID INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(100) NOT NULL,
  shared BOOLEAN NOT NULL DEFAULT FALSE,
  mimetype VARCHAR(100) NOT NULL,
  thumbnail VARCHAR(255) NOT NULL,
  filesize VARCHAR(100) NOT NULL,
  userID INT NOT NULL,
  PRIMARY KEY (fileID),
  FOREIGN KEY (userID) REFERENCES User (userID)
);
ALTER TABLE File ADD UNIQUE KEY `uidx` (name, mimetype, userID);

CREATE TABLE Friendship(
  friendshipID INT NOT NULL AUTO_INCREMENT,
  me INT NOT NULL,
  friend INT NOT NULL,
  PRIMARY KEY (friendshipID),
  FOREIGN KEY (me) REFERENCES User (userID),
  FOREIGN KEY (friend) REFERENCES User (userID)
);
